// <auto-generated />
using System;
using AssistantDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssistantDatabase.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241118084130_Colors")]
    partial class Colors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssistantDatabase.Model.DonePointDM", b =>
                {
                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PointId", "FinishDate");

                    b.ToTable("DonePoints");
                });

            modelBuilder.Entity("AssistantDatabase.Model.DoneTaskDM", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId", "FinishDate");

                    b.ToTable("DoneTasks");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnchorBegin")
                        .HasColumnType("bit");

                    b.Property<bool>("AnchorEnd")
                        .HasColumnType("bit");

                    b.Property<int>("AsdPersonId")
                        .HasColumnType("int");

                    b.Property<int>("CaregiverId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int?>("TimeBegin")
                        .HasColumnType("int");

                    b.Property<int?>("TimeEnd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsdPersonId");

                    b.HasIndex("CaregiverId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskPointDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MinTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskPoints");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaregiverId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.ToTable("Trigers");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerPointDM", b =>
                {
                    b.Property<int>("TriggerId")
                        .HasColumnType("int");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.HasKey("TriggerId", "PointId");

                    b.HasIndex("PointId");

                    b.ToTable("TriggerPoints");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerTaskDM", b =>
                {
                    b.Property<int>("TriggerId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TriggerId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TriggerTasks");
                });

            modelBuilder.Entity("AssistantDatabase.Model.UserDM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaregiverId")
                        .HasColumnType("int");

                    b.Property<string>("ColorsPalete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelectedASD")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssistantDatabase.Model.DonePointDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.TaskPointDM", "Point")
                        .WithMany("Done")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("AssistantDatabase.Model.DoneTaskDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.TaskDM", "Task")
                        .WithMany("Done")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.UserDM", "AsdPerson")
                        .WithMany()
                        .HasForeignKey("AsdPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssistantDatabase.Model.UserDM", "Caregiver")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsdPerson");

                    b.Navigation("Caregiver");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskPointDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.TaskDM", "Task")
                        .WithMany("Points")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.UserDM", "Caregiver")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caregiver");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerPointDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.TaskPointDM", "Point")
                        .WithMany("TriggerPoints")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantDatabase.Model.TriggerDM", "Trigger")
                        .WithMany("TriggerPoints")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerTaskDM", b =>
                {
                    b.HasOne("AssistantDatabase.Model.TaskDM", "Task")
                        .WithMany("TriggerTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssistantDatabase.Model.TriggerDM", "Trigger")
                        .WithMany("TriggerTasks")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskDM", b =>
                {
                    b.Navigation("Done");

                    b.Navigation("Points");

                    b.Navigation("TriggerTasks");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TaskPointDM", b =>
                {
                    b.Navigation("Done");

                    b.Navigation("TriggerPoints");
                });

            modelBuilder.Entity("AssistantDatabase.Model.TriggerDM", b =>
                {
                    b.Navigation("TriggerPoints");

                    b.Navigation("TriggerTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
